### ISSUE TITLE
TypeError : this.Promise.map is not a function

### ISSUE THREAD

**Issue by fidelis** [ice-services/moleculer-realworld-example-app#9]
npm run dev

http://localhost:3000/#/

[2020-05-07T20:24:16.263Z] ERROR ip-c613f45b-11900/API:    Request error! TypeError : this.Promise.map is not a function 
 TypeError: this.Promise.map is not a function
    at Service.transformResult (D:\moleculer-realworld-example-app\services\articles.service.js:570:25)    at D:\moleculer-realworld-example-app\services\articles.service.js:223:27

**Comment by icebob** [comment]
Please change it to `this.Promise.mapSeries()`. I will fix it.
